services:
  api:
    build: ./api
    image: mlx-deploy-search-api
    ports:
      - "8000:8000"

  front:
    build: ./front
    image: mlx-deploy-search-front
    environment:
      - API_HOST=api
      - API_PORT=8000
    ports:
          - "8501:8501"
    depends_on:
      - api

  nginx:
    build: ./nginx
    image: nginx:latest
    ports:
      - "80:8080"
    depends_on:
      - api
      - front