services:
  api:
    build: ./api
    expose: 
      - 8000
    networks:
      - app-network

  front:
    build: ./front
    environment:
      - API_HOST=api
      - API_PORT=8000
    expose:
      - 8501
    depends_on:
      - api
    networks:
      - app-network

  nginx:
    build: 
      context: ./nginx
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
    ports:
      - "80:8080"
      - "443:443"
    depends_on:
      - api
      - front
    networks:
      - app-network

networks:
  app-network:
    driver: bridge