FROM postgres:15

# # Set environment variables
# ENV POSTGRES_DB=user_logs
# ENV POSTGRES_USER=logger
# ENV POSTGRES_PASSWORD=secure_password

# # Create directory for initialization scripts
# WORKDIR /docker-entrypoint-initdb.d

# # Add initialization SQL script
# # COPY ./init.sql .

# # Expose the default PostgreSQL port
EXPOSE 5432